### ISSUE TITLE
Put binaries inside github

### ISSUE THREAD

**Issue by netei** [svent/sift#18]
It would be better to put the binaries inside github (in the releases), because your website uses http instead of https (http://sift-tool.org/download.html)

**Comment by svent** [comment]
The website has always been available via HTTPS for exactly this reason (publishing binaries) and even sends a HSTS header to improve security.
It was also available via HTTP - I just implemented an automatic redirect to the HTTPS version. I will keep publishing the binaries there as I do not see any advantage in using github for that at the moment.

**Comment by netei** [comment]
No problem if the site supports https. You should probably update the url at the top of your github repo

**Comment by matrixik** [comment]
Would be nice if you could reconsider adding binaries to github releases page because then users could for example use [zplug](https://github.com/zplug/zplug) to always have up to date bins (maybe you could do it automatically).

For example this will install, add to PATH and update when I want https://github.com/junegunn/fzf:
```
zplug "junegunn/fzf-bin", \
    from:gh-r, \
    as:command, \
    rename-to:fzf, \
    use:"*linux*amd64*"
```
