### ISSUE TITLE
a question about zip/gz files

### ISSUE THREAD

**Issue by jgranduel** [svent/sift#19]
Hi, 

thanks for your project.
I've seen that sift deals with zip files

```
-z, --zip
    search content of compressed .gz files (default: off)
```

is it only gz files or plain zip? are other format planned?
Will it be possible to search inside commonly used zipped files (OpenXML as docx, OpenOffice as odt or Java jar)?

Could the out be more precise than : "Binary file matches: filename.tar.gz"?
Thanks again, 
Best regards,
jgr

**Comment by svent** [comment]
Unfortunately, right now only gz files are supported - those files are much easier to handle as they can still be read as a single stream.
.zip files need to be unpacked and can contain many different files - right now I do not plan to support such file types.

The "Binary file matches" output does not contain more info (like the match found) because that match will often contain control characters etc. that cannot be normally printed and quite often destroy the output in the terminal.

**Comment by jgranduel** [comment]
Thanks a lot for the quick answer. I thought it might be as easy to read zip as gz when i saw https://golang.org/src/archive/zip/example_test.go. But OK, it's not! (But still requesting for it!).

As for output, I guessed it was for that reason.

**Comment by richrumble** [comment]
zcat file.zip |sift should work too. zcat can do zip, tar.gz, gz and bz2 if I'm not mistaken, so in theory you can do docx etc... I've not tried.

**Comment by svent** [comment]
zcat seems to work if the zip contains only one file, but docx etc. contain multiple files.

sift only supports searching directly in plain files and complex container formats like zip will not be supported in the future (where would this end? sift could also support RAR/PDF/etc.) - I guess there are better tools for that job.
