### ISSUE TITLE
Search path keep expanded. (in Git Bash, Windows)

### ISSUE THREAD

**Issue by kybin** [svent/sift#31]
in Git Bash, during searching I could see these errors.

```
Error: cannot open file 'C:\Users\Administrator\AppData\Local\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Temp\Administrator.20150930.1444.ma-ScriptEditor-2': open C:\Users\Administrator\AppData\Local\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Temp\Administrator.20150930.1444.ma-ScriptEditor-2: The system cannot find the path specified.
Error: cannot open file 'C:\Users\Administrator\AppData\Local\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Temp\Administrator.20150930.1444.ma-ScriptEditor-3': open C:\Users\Administrator\AppData\Local\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Application Data\Temp\Administrator.20150930.1444.ma-ScriptEditor-3: The system cannot find the path specified.
```

... it reports same error repeatedly.

There is no 'Application Data' folder in AppData\Local. The actual path is AppData\Local\Temp.

It seems gitbash's only problem. When I searching from cmd no error occured.

**Comment by svent** [comment]
I did some research on this, 'Application Data' seems to be a junction (not a folder) pointing recursively to the parent directory on some versions of windows (see [link 1](http://answers.microsoft.com/en-us/windows/forum/windows_7-files/infinite-application-data-folders-and-subfolders/e5c13e20-2271-4329-bde8-c93cb1988139), [link 2](http://answers.microsoft.com/en-us/windows/forum/windows_7-files/why-are-there-multiple-layers-of-application-data/4ec2c92c-a691-432b-b86a-c76d2b9a3faa)), leading to this behavior.

Unfortunately, I do not know yet exactly what gitbash changes in the environment so that this problem arises (as sift seems to be able to handle this when used from a normal command shell).

What version of Windows did you use here? I just tested this with a Windows 7 installation + gitbash but could not reproduce this behavior so far.

**Comment by kybin** [comment]
My environment is Windows7 + git version 2.6.1.windows.1
I choose my git bash to use mintty. may be related with it?

Thank you for digging this.

**Comment by kybin** [comment]
Ah.. sorry, It's my fault.

Application Data folder(junction) is literally in there and linked to It's parent directory. So the recursion starts.

So maybe we need option for allow (or disallow) following links?

**Comment by svent** [comment]
sift does not even follow symlinks, but unfortunately a junction on windows is not detected as a "symlink".
I guess following these junctions is not a problem in normal cases, but of course recursive directories structures lead to problems.
It seems that (at least currently) these kind of juctions are not easily (i.e. without ugly workarounds) detectable from golang. I would suggest to use something like `--exclude-dirs 'Application Data'` to handle these cases.
