### ISSUE TITLE
Request: Allow --type, --ext and --files

### ISSUE THREAD

**Issue by MiguelLatorre** [svent/sift#58]
It would be great to select files like (for example):

<pre>
sift --type=cc,cpp --files=CMakeLists.txt --files=Makefile --ext=mak,def
</pre>

Currently, one can use multiple --type, --file and --ext, but not mixed.
Maybe, allowing creating new types in .sift.conf?

I'm very close to fully replace <i>ack</i> with <b>sift</b>!
Great work.

**Comment by svent** [comment]
If I understand this correctly, you would want to combine the filtering options via OR instead of AND?

That is not possible with the current design of the filtering options - as you suggest, allowing custom types in the sift config would be the best solution in that case. If I understood the request correctly, I will implement it that way.

**Comment by MiguelLatorre** [comment]
I think your interpretation is correct, but just in case:
I wanted to grep for <i>makefile</i> files.
If I have, to simplify, in current directory, the files:

<pre>
Makefile
a.mak
</pre>

Reading the docs, I thought I should use something like:

<pre>
sift --files=Makefile --ext=mak --targets
</pre>

I expected to see both files printed, but I saw none.

**Comment by svent** [comment]
Thanks for the clarification. It is correct that sift shows nothing, as those options mean "all files named 'Makefile' AND having the extension '.mak'".

I think custom types are the best (and most flexible) option here, so I will implement that.

**Comment by svent** [comment]
This is now implemented, please see this blog post: https://svent.github.io
