### ISSUE TITLE
Support for plan 9?

### ISSUE THREAD

**Issue by aerth** [svent/sift#71]
Builds fine, but seems like whatever I `sift` just doesn't show up in output.

```
go get -v github.com/svent/sift
cd $GOPATH/src/github.com/svent/sift
sift sift
# no output
```

Here is the C source for Plan 9's grep command.

http://plan9.bell-labs.com/sources/plan9/sys/src/cmd/grep/

Go version 1.4.3

Feel free to close this if you don't plan on adding plan 9 support

**Comment by svent** [comment]
I dropped Plan 9 support after sift version 0.4.0 as I started using a library for terminal detection that does not fully support Plan 9.
It might work if you specify the search target, i.e. use `sift pattern .` to search in the current dirctory instead of just `sift pattern`.
Alternatively, you could try an older version:
https://sift-tool.org/downloads/sift/sift_0.4.0_plan9_386.zip

**Comment by aerth** [comment]
Thanks for the link to the older version. Didnt realize the terminal detection going on!
