### ISSUE TITLE
Feature Request: bash completion

### ISSUE THREAD

**Issue by robEllenberg** [svent/sift#75]
It would be nice to be able to complete options and arguments as with grep. The help listing is handy for looking up options / usages, but it would speed up typing to be able to directly complete them.

**Comment by svent** [comment]
The repository now contains a bash completion script:
https://github.com/svent/sift/blob/master/sift-completion.bash
The script uses sift to parse its own options and supported types instead of hard-coding them, so the completion script should work with upcoming versions of sift without the need to update the bash completion script itself.

**Comment by yermulnik** [comment]
@svent FYI: https://github.com/Homebrew/homebrew-core/pull/153762

**Comment by yermulnik** [comment]
@svent Are you reachable? The Bash completion script needs a tiny adjustment that I can create PR for, but it seems like you're not available, are you?

**Comment by svent** [comment]
@yermulnik I am, feel free to send a PR for that.

**Comment by yermulnik** [comment]
@svent Here you go: https://github.com/svent/sift/pull/125
Thank you.
